public class FirstClass {

    public void firstMethod(){
        String name = 'My Name is Shubham';
        system.debug(name);
        Account acc = new account();
        acc.name= 'SF05';
           insert acc;
    }
    
    public integer secondMethod(){
        integer a = 3;
        integer b = 5;
        integer sum = a+b;
        return sum;
    }
    
    public integer thirdmethod(integer a, integer b){
        integer sum = a+b;
        return sum;
    }
    
}